# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
