# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0002_auto_20160819_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
