# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0002_auto_20160830_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(default=2016),
        ),
    ]
