# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0003_auto_20160830_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2016)]),
        ),
    ]
